<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>DockPad</AssemblyName>
    <RootNamespace>DockPad</RootNamespace>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Version>1.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="app.ico"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="8.0.0"/>
  </ItemGroup>

</Project>
